from selenium.webdriver.common.by import By

class UIElementsLocators:
    TEXT_FIELD_INPUT= (By.ID, "textField")
    OUTPUT_TEXT_FIELD = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[1]/div[2]/div")
    TEXT_AREA_INPUT = (By.ID, "textArea")
    OUTPUT_TEXT_AREA_FIELD= (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[2]/div[2]/div")
    BUTTON_CLICK_ME = (By.ID, "ui-click-button")
    OUTPUT_COUNT_CLIK_ME = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[3]/div[2]/div")
    CHECKBOX_SINGLE = (By.ID, "ui-single-checkbox")
    OUTPUT_CHECKBOX_SINGLE = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[4]/div[2]/div")
    CHECKBOX_OPTION1 = (By.ID, "ui-checkbox-option1")
    CHECKBOX_OPTION2 = (By.ID, "ui-checkbox-option2")
    CHECKBOX_OPTION3 = (By.ID, "ui-checkbox-option3")
    OUTPUT_MULTICHECK_BOX = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[5]/div[2]/div")
    RADIO_BUTTON_R1 = (By.CSS_SELECTOR, "[data-testid='ui-radio-Radio 1']")
    RADIO_BUTTON_R2 = (By.CSS_SELECTOR, "[data-testid='ui-radio-Radio 2']")
    RADIO_BUTTON_R3 = (By.CSS_SELECTOR, "[data-testid='ui-radio-Radio 3']")
    OUTPUT_RADIO_BUTTONS = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[6]/div[2]/div")
    DROPDOWN = (By.CSS_SELECTOR,"[data-testid='ui-single-dropdown']")
    OUTPUT_DROPDOWN = (By.XPATH, "//*[@id='root']/div[2]/div[1]/div[7]/div[2]/div")
